test_suites:
    - name: lint
      script_path: ../okta-auth-js/scripts
      sort_order: '1'
      timeout: '60'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit
      script_path: ../okta-auth-js/scripts
      sort_order: '2'
      timeout: '10'
      script_name: unit
      criteria: MERGE
      queue_name: small
    - name: integration
      script_path: ../okta-auth-js/scripts
      sort_order: '2'
      timeout: '10'
      script_name: integration
      criteria: MERGE
      queue_name: small
    - name: validate-bundles
      script_path: ../okta-auth-js/scripts
      sort_order: '2'
      timeout: '10'
      script_name: validate-bundles
      criteria: MERGE
      queue_name: small
    - name: e2e
      script_path: ../okta-auth-js/scripts
      sort_order: '3'
      timeout: '15'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: e2e-refresh-token
      script_path: ../okta-auth-js/scripts
      sort_order: '4'
      timeout: '10'
      script_name: e2e-refresh-token
      criteria: MERGE
      queue_name: small
    - name: e2e-mfa
      script_path: ../okta-auth-js/scripts
      sort_order: '5'
      timeout: '10'
      script_name: e2e-mfa
      criteria: MERGE
      queue_name: small
    - name: e2e-oie
      script_path: ../okta-auth-js/scripts
      sort_order: '6'
      timeout: '15'
      script_name: e2e-oie
      criteria: MERGE
      queue_name: small
    - name: e2e-samples
      script_path: ../okta-auth-js/scripts
      sort_order: '7'
      timeout: '20'
      script_name: e2e-samples
      criteria: MERGE
      queue_name: small
    - name: e2e-samples-express-web-no-oidc
      script_path: ../okta-auth-js/scripts
      sort_order: '8'
      timeout: '10'
      script_name: e2e-samples-express-web-no-oidc
      criteria: MERGE
      queue_name: small
    - name: e2e-samples-express-web-with-oidc
      script_path: ../okta-auth-js/scripts
      sort_order: '9'
      timeout: '10'
      script_name: e2e-samples-express-web-with-oidc
      criteria: MERGE
      queue_name: small
    - name: e2e-samples-express-static-spa
      script_path: ../okta-auth-js/scripts
      sort_order: '11'
      timeout: '10'
      script_name: e2e-samples-static-spa
      criteria: MERGE
      queue_name: small
    - name: e2e-samples-webpack-spa
      script_path: ../okta-auth-js/scripts
      sort_order: '12'
      timeout: '10'
      script_name: e2e-samples-webpack-spa
      criteria: MERGE
      queue_name: small
    - name: e2e-samples-express-embedded-sign-in-widget
      script_path: ../okta-auth-js/scripts
      sort_order: '13'
      timeout: '10'
      script_name: e2e-samples-express-embedded-sign-in-widget
      criteria: MERGE
      queue_name: small
    - name: publish
      script_path: ../okta-auth-js/scripts
      sort_order: '9'
      timeout: '60'
      script_name: publish
      criteria: MERGE
      queue_name: small
    # Sauce labs tests are flaky due to the free account we are currently using
    # Re-enable this task on bacon once we have an paid account
    # - name: e2e-saucelabs 
    #   script_path: ../okta-auth-js/scripts
    #   sort_order: '8'
    #   timeout: '60'
    #   script_name: e2e-saucelabs
    #   criteria: MERGE
    #   queue_name: small