language: node_js

node_js:
  - '10'

install:
  - yarn install --frozen-lockfile
  - npm install -g codecov

script:
  - ./scripts/travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: false

addons:
  chrome: stable
